import { ReactNode } from "react";
import Head from "next/head";

const Layout = ({
  title = "T3 Blog",
  children,
}: {
  title?: string;
  children: ReactNode;
}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ maxWidth: "1024px", margin: "0 auto" }}>{children}</div>
    </>
  );
};

export default Layout;
